language: rust
os:
  - linux
  - osx
addons:
  apt:
    packages:
      - libasound2-dev
      - libudev-dev
      - libssl-dev
env:
  global:
    - RUST_BACKTRACE=1
  matrix:
    - WASM=0
rust:
  - stable
  - nightly
matrix:
  include:
    - rust: stable
      env: WASM=1
      install:
        - rustup target add wasm32-unknown-unknown
        - cargo install -f cargo-web
      script:
        - cargo web check --features stdweb
  allow_failures:
    - rust: nightly
  fast_finish: true
