[package]
name = "quick-fs"
version = "0.1.0"
authors = ["Ryan Goldstein <ryanisaacg@gmail.com>"]
edition = "2018"

[features]
"web_sys" = ["web-sys", "js-sys", "wasm-bindgen"]

[dependencies]
futures-preview = { version = "=0.3.0-alpha.17" }

[target.'cfg(target_arch = "wasm32")'.dependencies.stdweb]
version = "0.4.17"
optional = true

[target.'cfg(target_arch = "wasm32")'.dependencies.web-sys]
version = "0.3.24"
optional = true
features = [
    "XmlHttpRequest",
    "XmlHttpRequestEventTarget",
    "XmlHttpRequestResponseType",
]

[target.'cfg(target_arch = "wasm32")'.dependencies.js-sys]
version = "0.3.25"
optional = true

[target.'cfg(target_arch = "wasm32")'.dependencies.wasm-bindgen]
version = "0.2.48"
optional = true
